InterceptingClientHttpRequestspring:
  shardingsphere:
    datasource: # 配置数据源
      names: m1,s0,s1 # 分库的逻辑库名,可配置多个
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m1: # 主服务器
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.110.100:3307/user_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      s0: # 从服务器1
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.110.100:3308/user_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      s1: # 从服务器2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.110.100:3308/user_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
    sharding:
      binding-tables:
        - t_user
      # 主库从库逻辑数据源定义 ds0
      master-slave-rules:
        ds0:
          master-data-source-name: m1
          slave-data-source-names: [s0,s1]
          #load-balance-algorithm-class-name: #从库负载均衡算法类名称。该类需实现MasterSlaveLoadBalanceAlgorithm接口且提供无参数构造器
          load-balance-algorithm-type: RANDOM #从库负载均衡算法类型，可选值：ROUND_ROBIN，RANDOM。若`load-balance-algorithm-class-name`存在则忽略该配置
#      default-data-source-name: m1
#      default-database-strategy:
#        standard:
#          sharding-column: user_id
#          precise-algorithm-class-name: org.wmc.integrated.config.DbShardingAlgorithm
#      default-table-strategy:
#        standard:
#          sharding-column: user_id
#          precise-algorithm-class-name: org.wmc.integrated.config.MyPreciseShardingAlgorithm
#        default-key-generator:
#          column: userId
#          type: MyKeyGenerator
      tables:
        # 配置user_db数据库里面t_user 专库专表
        t_user:
          actual-data-nodes: ds0.t_user
          table-strategy: #分表策略
            inline:
              sharding-column: cid #分片路由标准
              algorithm-expression: t_user #t_user_$->{cid % 2 + 1} #分片算法表达式
#          table-strategy: #分表策略
#            standard:
#              sharding-column: user_id
#              precise-algorithm-class-name: org.wmc.integrated.config.MyPreciseShardingAlgorithm
          key-generator:
            column: user_id
            #type: SNOWFLAKE
            type: MyKeyGenerator
    props:
      sql:
        show: true # 开启sql日志输出

