spring:
  shardingsphere:
    datasource: # 配置数据源
      names: m1,m2,m0,m3 # 分库的逻辑库名,可配置多个
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m1: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m2: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m0: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m3: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        #        driver-class-name: com.mysql.cj.jdbc.Driver
        #        url: jdbc:mysql://localhost:3306/course_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
        #        username: root
        #        password: 123456
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://localhost:3306/course_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
        username: root
        password: 123456

    sharding:
      default-data-source-name: m3
      default-database-strategy:
        standard:
          sharding-column: cid
          precise-algorithm-class-name: org.wmc.integrated.config.DbShardingAlgorithm
      default-table-strategy:
        standard:
          sharding-column: cid
          precise-algorithm-class-name: org.wmc.integrated.config.MyPreciseShardingAlgorithm
      default-key-generator:
        column: cid
        type: MyKeyGenerator
      #      tables:
      #        course:
      #          #actual-data-nodes: m$->{[1,4]}.course_$->{1..2}
      #          actual-data-nodes: m$->{0..3}.course_$->{1..2}
      #        t_udict:
      #          key-generator:
      #            column: dictid
      #            type: SNOWFLAKE
      broadcast-tables: t_udict
    props:
      sql:
        show: true # 开启sql日志输出

