spring:
  shardingsphere:
    datasource: # 配置数据源
      names: m1,m2 # 分库的逻辑库名,可配置多个
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m1: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      # 配置数据源的具体内容，包含连接池，驱动，地址，用户名，密码
      m2: # 逻辑库名
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 123456
      # 指定course表分布的情况，配置表在哪个数据库里，表的名称都是什么 m1.course_1,m1.course_2
    sharding:
      tables:
        course:
          # 分库策略
          database-strategy:
            #            inline:
            #              sharding-column: user_id
            #              algorithm-expression: m$->{user_id % 2 + 1}
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: org.wmc.integrated.config.DbShardingAlgorithm
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
          table-strategy: #分表策略
            #            inline:
            #              sharding-column: cid #分片路由标准
            #              algorithm-expression: course_$->{cid % 2 + 1} #分片算法表达式
            standard:
              sharding-column: cid
              precise-algorithm-class-name: org.wmc.integrated.config.MyPreciseShardingAlgorithm
          key-generator:
            column: cid
            type: MyKeyGenerator
    props:
      sql:
        show: true # 开启sql日志输出

